apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: redis
spec:
  sentinel:
    replicas: 3
    resources:
      requests:
        cpu: 0.1
      limits:
        memory: 100Mi
  redis:
    replicas: 3
    resources:
      requests:
        cpu: 0.1
        memory: 100Mi
      limits:
        cpu: 0.4
        memory: 500Mi
